In [3]:
import pandas as pd

# 2. 판다스 객체 생성
- 시리즈: 레이블을 갖는 1차원 배열
- 데이터 프레임: 레이블을 갖는 행과 열을 갖는 2차원 배열

In [2]:
score = pd.Series([95, 90, 85, 90, 95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [3]:
# 인덱스 지정
s = pd.Series([90, 80, 95], index=['A', 'B', 'C'])

In [4]:
print(s)

A    90
B    80
C    95
dtype: int64


In [6]:
import numpy as np
arr = np.arange(12).reshape(4,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
df = pd.DataFrame(arr)
print(df)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [9]:
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [10]:
df = pd.DataFrame({'name': ['aaa', 'bbb', 'ccc'],
                  'score': [90, 80, 95],
                  'dept': ['com', 'eng', 'math']})
df

name  score  dept
0  aaa     90   com
1  bbb     80   eng
2  ccc     95  math

In [11]:
import os

In [13]:
os.getcwd()

'/Users/yeonsoo/비즈니스프로그래밍/BP2022-2/lecture'

In [14]:
df = pd.read_csv('/Users/yeonsoo/비즈니스프로그래밍/BP2022-2/data/weather1.csv')

In [15]:
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

# 3. 판다스 데이터 확인하기
- 데이터 확인을 위한 함수(메소드)와 속성

# 6. 판다스 데이터 가공하기
- 칼럼(변수) 삭제/생성하기
- 칼럼 이름 변경
- 데이터 형변환
- 데이터 병합하기

In [1]:
import os
path = os.getcwd()

In [4]:
dust = pd.read_excel(path + '/data/dust1.xlsx')

In [7]:
# 칼럼(변수) 삭제하기
dust.drop(['지역', '망', '측정소코드'], axis=1, inplace=True) # axis=0 행 삭제

In [9]:
# 새로운 칼럼 생성하기
dust['city'] = '서울'

In [11]:
# 칼럼 이름 변경
dust.rename(columns={'측정소명': 'name',
                    '측정일시': 'date',
                    '주소': 'addr'}, inplace=True)

In [14]:
# 데이터 형변환
dust.dtypes # 각 칼럼의 데이터 타입 확인

name     object
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10    float64
PM25    float64
addr     object
city     object
dtype: object

In [15]:
dust['date'] = dust['date'].astype(str)

In [17]:
dust['date']  = dust['date'].str.slice(0,8) # 시간은 잘라내기

In [18]:
dust

name      date    SO2   CO     O3    NO2  PM10  PM25              addr  \
0    송파구  20210401  0.004  1.0  0.002  0.066  50.0  18.0  서울 송파구 백제고분로 236   
1    송파구  20210401  0.004  0.8  0.002  0.058  48.0  20.0  서울 송파구 백제고분로 236   
2    송파구  20210401  0.004  0.8  0.002  0.055  44.0  20.0  서울 송파구 백제고분로 236   
3    송파구  20210401  0.003  0.8  0.002  0.055  40.0  20.0  서울 송파구 백제고분로 236   
4    송파구  20210401  0.004  0.8  0.002  0.053  38.0  17.0  서울 송파구 백제고분로 236   
..   ...       ...    ...  ...    ...    ...   ...   ...               ...   
715  송파구  20210430  0.002  0.5  0.039  0.020  69.0  33.0  서울 송파구 백제고분로 236   
716  송파구  20210430  0.002  0.5  0.039  0.019  76.0  34.0  서울 송파구 백제고분로 236   
717  송파구  20210430  0.002  0.5  0.037  0.018  71.0  31.0  서울 송파구 백제고분로 236   
718  송파구  20210430  0.002  0.5  0.040  0.016  46.0  22.0  서울 송파구 백제고분로 236   
719  송파구  20210430  0.002  0.4  0.039  0.016  34.0  18.0  서울 송파구 백제고분로 236   

    city  
0     서울  
1     서울  
2     서울  
3     서울  
4     서울  
..   ...  
715   서울  
716   서울  
717   서울  
718   서울  
719   서울  

[720 rows x 10 columns]

In [21]:
# 데이터 병합하기
s1 = pd.read_excel(path+'/data/nation.xlsx')
s2 = pd.read_excel(path+'/data/code.xlsx')

In [22]:
s1

국적코드 성별    입국객수    증가수
0  A01  남  125000   8000
1  A01  여  130000  10000
2  A05  남     300     10
3  A05  여     200     50
4  A06  남  158912  24486
5  A06  여  325000  63466

In [23]:
s2

국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타

In [24]:
pd.merge(s1, s2, on='국적코드')

국적코드 성별    입국객수    증가수  국적명
0  A01  남  125000   8000  필리핀
1  A01  여  130000  10000  필리핀
2  A05  남     300     10   호주
3  A05  여     200     50   호주
4  A06  남  158912  24486  베트남
5  A06  여  325000  63466  베트남

In [25]:
s1.groupby('국적코드').sum()

입국객수    증가수
국적코드               
A01   255000  18000
A05      500     60
A06   483912  87952

In [26]:
s1.groupby(['국적코드', '성별']).sum()

입국객수    증가수
국적코드 성별               
A01  남   125000   8000
     여   130000  10000
A05  남      300     10
     여      200     50
A06  남   158912  24486
     여   325000  63466